#!/usr/bin/env bash
# The one place a neosea version number comes from (the mem-manager scheme):
#   code  10000 + commits on HEAD     name  git describe --tags --always --dirty
# Releasing is tagging. Unknown is 0 / "unknown", never a plausible number.
#   ./scripts/version.sh [code|name|both|header PATH]
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
code=0
name="unknown"
if git -C "$HERE" rev-parse --git-dir >/dev/null 2>&1; then
    if [ -f "$(git -C "$HERE" rev-parse --git-dir)/shallow" ]; then
        echo "version.sh: shallow clone -- 'git fetch --unshallow' for a real build number" >&2
    else
        commits=$(git -C "$HERE" rev-list --count HEAD 2>/dev/null || echo 0)
        [ "$commits" -gt 0 ] && code=$((10000 + commits))
    fi
    name=$(git -C "$HERE" describe --tags --match 'v[0-9]*' --always --dirty 2>/dev/null || echo unknown)
fi
write_header() {
    local out="$1" tmp
    tmp="$(mktemp)"
    cat >"$tmp" <<EOH
#pragma once
// Generated by scripts/version.sh -- do not edit, do not commit.
namespace neosea {
inline constexpr int         kBuild       = ${code};
inline constexpr const char* kVersionName = "${name}";
}
EOH
    if [ -f "$out" ] && cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv "$tmp" "$out"; fi
}
case "${1:-both}" in
    code) echo "$code" ;;
    name) echo "$name" ;;
    both) echo "$code $name" ;;
    header) [ $# -ge 2 ] || { echo "usage: $0 header PATH" >&2; exit 2; }; write_header "$2" ;;
    *) echo "usage: $0 [code|name|both|header PATH]" >&2; exit 2 ;;
esac
